In [4]:
!pip install pandas-datareader
!pip install yfinance

Requirement already satisfied: pandas-datareader in e:\anaconda\lib\site-packages (0.11.1)
Requirement already satisfied: lxml in e:\anaconda\lib\site-packages (from pandas-datareader) (5.3.0)
Requirement already satisfied: pandas>=2.1.4 in e:\anaconda\lib\site-packages (from pandas-datareader) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in e:\anaconda\lib\site-packages (from pandas-datareader) (2.32.5)
Requirement already satisfied: setuptools in e:\anaconda\lib\site-packages (from pandas-datareader) (80.9.0)
Requirement already satisfied: numpy>=1.26.0 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2025.2)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.4->pandas-datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2026.5.20)
Collecting yfinance
  Downloading yfinance-1.5.2-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in e:\anaconda\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in e:\anaconda\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in e:\anaconda\lib\site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in e:\anaconda\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in e:\anaconda\lib\site-packages (from yfinance) (2025.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.2.6-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in e:\anaconda\lib\site-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: protobuf>=3.19.0 in e:\anaconda\lib\site-packages (from yfinance) (5.29.3)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.1.1-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in e:\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in e:\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in e:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in e:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in e:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in e:\anaconda\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in e:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.5.2-py2.py3-none-any.whl (144 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 347.3 kB/s eta 0:00:04
   ------------ --------------------------- 0.5/1.7 MB 347.3 kB/s eta 0:00:04
   ------------ --------------------------- 0.5/1.7 MB 347.3 kB/s eta 0:00:04
   ------------------ --------------------- 0.8/1.7 MB 362.2 kB/s eta 0:00:03
   ------------------------- -------------- 1.0/1.7 MB 449.3 kB/s eta 0:00:02
   ------------------------- -------------- 1.0/1.7 MB 449.3 kB/s eta 0:00:02
   ------------------------------- -------- 1.3/1.7 MB 489.5 kB/s eta 0:00:01
   ------------------------------- -------- 1.3/1.7 MB 489.5 kB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 525.7 kB/s  0:00:03
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.2.6-py3-none-any.whl (173 kB)
Downloading websockets-16.1.1-cp313-cp313-win_amd64.whl (180 kB)
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance

   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   ---------------------------------------- 0/5 [peewee]
   -------- ------------------------------- 1/5 [multitasking]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ---------------- ----------------------- 2/5 [websockets]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   ------------------------ --------------- 3/5 [curl_cffi]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   -------------------------------- ------- 4/5 [yfinance]
   ---------------------------------------- 5/5 [yfinance]

Successfully installed curl_cffi-0.15.0 multitasking-0.0.13 peewee-4.2.6 websockets-16.1.1 yfinance-1.5.2

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/yfinance/

In [5]:
import pandas as pd
import numpy as np
import datetime as dt
from pandas_datareader import data as pdr
import yfinance as yf

### Phase 1 : Data collection

In [68]:

# Stock data collection
# Importing data of 50 stocks

stocks = ["AAPL","MSFT","NVDA","AVGO","ORCL",
    "AMZN","TSLA","HD","MCD","BKNG",
    "META","GOOGL","NFLX","DIS",
    "PG","KO","PEP","COST",
    "UNH","JNJ","ABBV","LLY","MRK",
    "JPM","BAC","WFC","GS","MS","BLK",
    "CAT","GE","HON","UPS","BA","DE",
    "XOM","CVX","COP",
    "NEE","DUK",
    "PLD","AMT",
    "LIN","SHW","FCX","ECL",
    "AMD","CRM","TMUS","ISRG"]

data = yf.download(stocks, start='2016-01-01', end=None)

print(data)

[*********************100%***********************]  50 of 50 completed

Price            Close                                                  \
Ticker            AAPL        ABBV         AMD         AMT        AMZN
Date
2016-01-04   23.709099   37.132977    2.770000   74.226463   31.849501
2016-01-05   23.114967   36.978279    2.750000   75.692558   31.689501
2016-01-06   22.662613   36.984726    2.510000   75.423912   31.632500
2016-01-07   21.706154   36.875137    2.280000   73.543289   30.396999
2016-01-08   21.820932   35.869637    2.140000   72.330521   30.352501
...                ...         ...         ...         ...         ...
2026-07-21  327.739990  256.100006  544.429993  163.389999  247.550003
2026-07-22  325.890015  253.300003  552.330017  166.059998  244.850006
2026-07-23  321.660004  256.920013  539.690002  164.649994  233.660004
2026-07-24  333.019989  259.359985  521.950012  166.669998  232.110001
2026-07-27  336.910004  256.910004  494.950012  166.740005  231.389999

Price                                                                   ...  \
Ticker            AVGO          BA        BAC        BKNG          BLK  ...
Date                                                                    ...
2016-01-04   10.836730  126.005104  13.054462   48.778641   256.778748  ...
2016-01-05   10.474188  126.516327  13.054462   47.420296   257.441711  ...
2016-01-06   10.152009  124.507393  12.776369   46.872723   254.512283  ...
2016-01-07    9.829070  119.287819  12.315530   45.716488   243.388580  ...
2016-01-08    9.764332  116.579369  12.077161   44.532436   237.260071  ...
...                ...         ...        ...         ...          ...  ...
2026-07-21  386.500000  204.800003  61.220001  179.399994  1038.239990  ...
2026-07-22  396.809998  208.649994  61.619999  177.860001  1056.630005  ...
2026-07-23  392.470001  209.229996  61.279999  172.830002  1037.160034  ...
2026-07-24  381.920013  209.520004  62.049999  177.460007  1055.670044  ...
2026-07-27  383.220001  211.500000  62.130001  186.789993  1062.140015  ...

Price        Volume                                                           \
Ticker          PEP        PG      PLD      SHW     TMUS       TSLA      UNH
Date
2016-01-04  6689000  11529800  2852100  3405000  4614200  102406500  4991000
2016-01-05  4893800   8133700  3262700  2271900  5553600   47802000  2816800
2016-01-06  5483400   9551000  3385000  2370900  7243800   56686500  2677300
2016-01-07  5440000  11973900  3902800  2640900  8091300   53314500  5277200
2016-01-08  4853500   9676400  4161500  3592800  3512900   54421500  4422400
...             ...       ...      ...      ...      ...        ...      ...
2026-07-21  7989500   7027600  3263900  1285500  3725700   32735300  6833600
2026-07-22  6198700   5371200  6649300  2765700  4476300   30646100  4234100
2026-07-23  7755700   6499200  7444400  2446300  9626400  115606400  4868700
2026-07-24  7968300   6620700  6395400  2021300  5629200   62760000  3752500
2026-07-27  7237900   7301800  4110500  3207800  5494800   44754900  4615700

Price
Ticker          UPS       WFC       XOM
Date
2016-01-04  3730800  25985400  20400100
2016-01-05  2839600  14759600  11993500
2016-01-06  2443000  20026400  18826900
2016-01-07  3790800  30425600  21263800
2016-01-08  3941100  22981400  19033600
...             ...       ...       ...
2026-07-21  4349600  17605300  13145300
2026-07-22  3196900  15478700  13788700
2026-07-23  4198400  11220700  15822800
2026-07-24  3881100  11871400  12091600
2026-07-27  6719200  10379300  13955800

[2655 rows x 250 columns]

In [69]:
print(data.head())

Price           Close                                                    \
Ticker           AAPL       ABBV   AMD        AMT       AMZN       AVGO
Date
2016-01-04  23.709099  37.132977  2.77  74.226463  31.849501  10.836730
2016-01-05  23.114967  36.978279  2.75  75.692558  31.689501  10.474188
2016-01-06  22.662613  36.984726  2.51  75.423912  31.632500  10.152009
2016-01-07  21.706154  36.875137  2.28  73.543289  30.396999   9.829070
2016-01-08  21.820932  35.869637  2.14  72.330521  30.352501   9.764332

Price                                                     ...   Volume  \
Ticker              BA        BAC       BKNG         BLK  ...      PEP
Date                                                      ...
2016-01-04  126.005104  13.054462  48.778641  256.778748  ...  6689000
2016-01-05  126.516327  13.054462  47.420296  257.441711  ...  4893800
2016-01-06  124.507393  12.776369  46.872723  254.512283  ...  5483400
2016-01-07  119.287819  12.315530  45.716488  243.388580  ...  5440000
2016-01-08  116.579369  12.077161  44.532436  237.260071  ...  4853500

Price                                                                         \
Ticker            PG      PLD      SHW     TMUS       TSLA      UNH      UPS
Date
2016-01-04  11529800  2852100  3405000  4614200  102406500  4991000  3730800
2016-01-05   8133700  3262700  2271900  5553600   47802000  2816800  2839600
2016-01-06   9551000  3385000  2370900  7243800   56686500  2677300  2443000
2016-01-07  11973900  3902800  2640900  8091300   53314500  5277200  3790800
2016-01-08   9676400  4161500  3592800  3512900   54421500  4422400  3941100

Price
Ticker           WFC       XOM
Date
2016-01-04  25985400  20400100
2016-01-05  14759600  11993500
2016-01-06  20026400  18826900
2016-01-07  30425600  21263800
2016-01-08  22981400  19033600

[5 rows x 250 columns]

In [70]:
close_prices = data['Close']
print(close_prices)

Ticker            AAPL        ABBV         AMD         AMT        AMZN  \
Date
2016-01-04   23.709099   37.132977    2.770000   74.226463   31.849501
2016-01-05   23.114967   36.978279    2.750000   75.692558   31.689501
2016-01-06   22.662613   36.984726    2.510000   75.423912   31.632500
2016-01-07   21.706154   36.875137    2.280000   73.543289   30.396999
2016-01-08   21.820932   35.869637    2.140000   72.330521   30.352501
...                ...         ...         ...         ...         ...
2026-07-21  327.739990  256.100006  544.429993  163.389999  247.550003
2026-07-22  325.890015  253.300003  552.330017  166.059998  244.850006
2026-07-23  321.660004  256.920013  539.690002  164.649994  233.660004
2026-07-24  333.019989  259.359985  521.950012  166.669998  232.110001
2026-07-27  336.910004  256.910004  494.950012  166.740005  231.389999

Ticker            AVGO          BA        BAC        BKNG          BLK  ...  \
Date                                                                    ...
2016-01-04   10.836730  126.005104  13.054462   48.778641   256.778748  ...
2016-01-05   10.474188  126.516327  13.054462   47.420296   257.441711  ...
2016-01-06   10.152009  124.507393  12.776369   46.872723   254.512283  ...
2016-01-07    9.829070  119.287819  12.315530   45.716488   243.388580  ...
2016-01-08    9.764332  116.579369  12.077161   44.532436   237.260071  ...
...                ...         ...        ...         ...          ...  ...
2026-07-21  386.500000  204.800003  61.220001  179.399994  1038.239990  ...
2026-07-22  396.809998  208.649994  61.619999  177.860001  1056.630005  ...
2026-07-23  392.470001  209.229996  61.279999  172.830002  1037.160034  ...
2026-07-24  381.920013  209.520004  62.049999  177.460007  1055.670044  ...
2026-07-27  383.220001  211.500000  62.130001  186.789993  1062.140015  ...

Ticker             PEP          PG         PLD         SHW        TMUS  \
Date
2016-01-04   71.665527   58.231121   30.973532   76.986443   37.247654
2016-01-05   72.158928   58.416851   31.624039   77.297699   38.462151
2016-01-06   72.180710   57.852135   31.454016   75.061417   38.299572
2016-01-07   70.794861   57.346901   30.633480   73.003372   38.739471
2016-01-08   70.533630   56.447819   30.359962   73.063828   38.137012
...                ...         ...         ...         ...         ...
2026-07-21  135.000000  147.002625  149.940002  318.459991  190.770004
2026-07-22  135.649994  148.024994  144.699997  319.910004  190.940002
2026-07-23  134.949997  145.880997  145.119995  310.540009  170.419998
2026-07-24  136.639999  147.410004  147.630005  317.510010  180.089996
2026-07-27  139.789993  148.630005  147.259995  327.269989  177.210007

Ticker            TSLA         UNH         UPS        WFC         XOM
Date
2016-01-04   14.894000   97.893669   63.807011  39.475040   49.319614
2016-01-05   14.895333   98.078583   64.439415  39.460129   49.739849
2016-01-06   14.602667   97.078323   63.524437  38.706589   49.325985
2016-01-07   14.376667   94.220367   62.299961  37.602402   48.536480
2016-01-08   14.066667   92.598045   61.485859  36.975681   47.555927
...                ...         ...         ...        ...         ...
2026-07-21  378.929993  436.350006  116.339996  87.739998  151.710007
2026-07-22  374.010010  431.309998  115.839996  86.419998  154.449997
2026-07-23  319.690002  423.559998  114.099998  86.190002  156.889999
2026-07-24  313.029999  420.739990  114.790001  86.309998  156.940002
2026-07-27  309.220001  417.640015  112.949997  87.269997  154.770004

[2655 rows x 50 columns]

In [71]:
stock_prices = data.xs("Close", axis=1, level="Price")
stock_prices

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,23.709099,37.132977,2.770000,74.226463,31.849501,10.836730,126.005104,13.054462,48.778641,256.778748,...,71.665527,58.231121,30.973532,76.986443,37.247654,14.894000,97.893669,63.807011,39.475040,49.319614
2016-01-05,23.114967,36.978279,2.750000,75.692558,31.689501,10.474188,126.516327,13.054462,47.420296,257.441711,...,72.158928,58.416851,31.624039,77.297699,38.462151,14.895333,98.078583,64.439415,39.460129,49.739849
2016-01-06,22.662613,36.984726,2.510000,75.423912,31.632500,10.152009,124.507393,12.776369,46.872723,254.512283,...,72.180710,57.852135,31.454016,75.061417,38.299572,14.602667,97.078323,63.524437,38.706589,49.325985
2016-01-07,21.706154,36.875137,2.280000,73.543289,30.396999,9.829070,119.287819,12.315530,45.716488,243.388580,...,70.794861,57.346901,30.633480,73.003372,38.739471,14.376667,94.220367,62.299961,37.602402,48.536480
2016-01-08,21.820932,35.869637,2.140000,72.330521,30.352501,9.764332,116.579369,12.077161,44.532436,237.260071,...,70.533630,56.447819,30.359962,73.063828,38.137012,14.066667,92.598045,61.485859,36.975681,47.555927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-21,327.739990,256.100006,544.429993,163.389999,247.550003,386.500000,204.800003,61.220001,179.399994,1038.239990,...,135.000000,147.002625,149.940002,318.459991,190.770004,378.929993,436.350006,116.339996,87.739998,151.710007
2026-07-22,325.890015,253.300003,552.330017,166.059998,244.850006,396.809998,208.649994,61.619999,177.860001,1056.630005,...,135.649994,148.024994,144.699997,319.910004,190.940002,374.010010,431.309998,115.839996,86.419998,154.449997
2026-07-23,321.660004,256.920013,539.690002,164.649994,233.660004,392.470001,209.229996,61.279999,172.830002,1037.160034,...,134.949997,145.880997,145.119995,310.540009,170.419998,319.690002,423.559998,114.099998,86.190002,156.889999
2026-07-24,333.019989,259.359985,521.950012,166.669998,232.110001,381.920013,209.520004,62.049999,177.460007,1055.670044,...,136.639999,147.410004,147.630005,317.510010,180.089996,313.029999,420.739990,114.790001,86.309998,156.940002
2026-07-27,336.910004,256.910004,494.950012,166.740005,231.389999,383.220001,211.500000,62.130001,186.789993,1062.140015,...,139.789993,148.630005,147.259995,327.269989,177.210007,309.220001,417.640015,112.949997,87.269997,154.770004

In [72]:
stock_prices.head()

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,23.709099,37.132977,2.77,74.226463,31.849501,10.836730,126.005104,13.054462,48.778641,256.778748,...,71.665527,58.231121,30.973532,76.986443,37.247654,14.894000,97.893669,63.807011,39.475040,49.319614
2016-01-05,23.114967,36.978279,2.75,75.692558,31.689501,10.474188,126.516327,13.054462,47.420296,257.441711,...,72.158928,58.416851,31.624039,77.297699,38.462151,14.895333,98.078583,64.439415,39.460129,49.739849
2016-01-06,22.662613,36.984726,2.51,75.423912,31.632500,10.152009,124.507393,12.776369,46.872723,254.512283,...,72.180710,57.852135,31.454016,75.061417,38.299572,14.602667,97.078323,63.524437,38.706589,49.325985
2016-01-07,21.706154,36.875137,2.28,73.543289,30.396999,9.829070,119.287819,12.315530,45.716488,243.388580,...,70.794861,57.346901,30.633480,73.003372,38.739471,14.376667,94.220367,62.299961,37.602402,48.536480
2016-01-08,21.820932,35.869637,2.14,72.330521,30.352501,9.764332,116.579369,12.077161,44.532436,237.260071,...,70.533630,56.447819,30.359962,73.063828,38.137012,14.066667,92.598045,61.485859,36.975681,47.555927

In [73]:

benchmark = "SPY"

start_date = "2015-01-01"
end_date = None
import yfinance as yf

benchmark = "SPY"

benchmark_data = yf.download(
    benchmark,
    start=start_date,
    end=end_date,
    auto_adjust=True,
    progress=False
)

benchmark_prices = benchmark_data["Close"]
benchmark_prices.name = "SPY"
print(benchmark_data)

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date
2015-01-02  169.687805  170.885534  168.655289  170.472527  121465900
2015-01-05  166.623383  168.812312  166.317762  168.647112  169632600
2015-01-06  165.053909  167.449342  164.260931  166.928950  209151400
2015-01-07  167.110672  167.449340  165.929480  166.375521  125346700
2015-01-08  170.076065  170.290837  168.498390  168.514901  147217800
...                ...         ...         ...         ...        ...
2026-07-21  748.280029  749.039978  744.179993  746.289978   34324300
2026-07-22  747.409973  750.020020  746.369995  746.619995   32836200
2026-07-23  738.179993  742.559998  735.210022  739.369995   55437300
2026-07-24  738.929993  743.719971  737.289978  738.510010   44782000
2026-07-27  739.090027  745.530029  735.869995  744.909973   41402200

[2907 rows x 5 columns]

In [74]:
Benchmark_close_prices = benchmark_data["Close"]
Benchmark_close_prices

Ticker             SPY
Date
2015-01-02  169.687805
2015-01-05  166.623383
2015-01-06  165.053909
2015-01-07  167.110672
2015-01-08  170.076065
...                ...
2026-07-21  748.280029
2026-07-22  747.409973
2026-07-23  738.179993
2026-07-24  738.929993
2026-07-27  739.090027

[2907 rows x 1 columns]

In [75]:
stock_prices.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2655 entries, 2016-01-04 to 2026-07-27
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2655 non-null   float64
 1   ABBV    2655 non-null   float64
 2   AMD     2655 non-null   float64
 3   AMT     2655 non-null   float64
 4   AMZN    2655 non-null   float64
 5   AVGO    2655 non-null   float64
 6   BA      2655 non-null   float64
 7   BAC     2655 non-null   float64
 8   BKNG    2655 non-null   float64
 9   BLK     2655 non-null   float64
 10  CAT     2655 non-null   float64
 11  COP     2655 non-null   float64
 12  COST    2655 non-null   float64
 13  CRM     2655 non-null   float64
 14  CVX     2655 non-null   float64
 15  DE      2655 non-null   float64
 16  DIS     2655 non-null   float64
 17  DUK     2655 non-null   float64
 18  ECL     2655 non-null   float64
 19  FCX     2655 non-null   float64
 20  GE      2655 non-null   float64
 21  GOOGL   2655 non-null   float64
 22  GS      2655 non-null   float64
 23  HD      2655 non-null   float64
 24  HON     2655 non-null   float64
 25  ISRG    2655 non-null   float64
 26  JNJ     2655 non-null   float64
 27  JPM     2655 non-null   float64
 28  KO      2655 non-null   float64
 29  LIN     2655 non-null   float64
 30  LLY     2655 non-null   float64
 31  MCD     2655 non-null   float64
 32  META    2655 non-null   float64
 33  MRK     2655 non-null   float64
 34  MS      2655 non-null   float64
 35  MSFT    2655 non-null   float64
 36  NEE     2655 non-null   float64
 37  NFLX    2655 non-null   float64
 38  NVDA    2655 non-null   float64
 39  ORCL    2655 non-null   float64
 40  PEP     2655 non-null   float64
 41  PG      2655 non-null   float64
 42  PLD     2655 non-null   float64
 43  SHW     2655 non-null   float64
 44  TMUS    2655 non-null   float64
 45  TSLA    2655 non-null   float64
 46  UNH     2655 non-null   float64
 47  UPS     2655 non-null   float64
 48  WFC     2655 non-null   float64
 49  XOM     2655 non-null   float64
dtypes: float64(50)
memory usage: 1.0 MB

In [78]:
Benchmark_close_prices.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2907 entries, 2015-01-02 to 2026-07-27
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SPY     2907 non-null   float64
dtypes: float64(1)
memory usage: 45.4 KB

In [79]:
Benchmark_close_prices.describe().T

,count,mean,std,min,25%,50%,75%,max
Ticker,,,,,,,,
SPY,2907.0,354.090173,158.179521,154.161621,224.172623,316.905029,434.725418,757.618225