In [1]:
!pip install pandas-datareader
!pip install yfinance

Requirement already satisfied: pandas-datareader in e:\anaconda\lib\site-packages (0.11.1)
Requirement already satisfied: lxml in e:\anaconda\lib\site-packages (from pandas-datareader) (5.3.0)
Requirement already satisfied: pandas>=2.1.4 in e:\anaconda\lib\site-packages (from pandas-datareader) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in e:\anaconda\lib\site-packages (from pandas-datareader) (2.32.5)
Requirement already satisfied: setuptools in e:\anaconda\lib\site-packages (from pandas-datareader) (80.9.0)
Requirement already satisfied: numpy>=1.26.0 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2025.2)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.4->pandas-datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\anaconda\lib\site-packages (from requests>=2.19.0->pandas-datareader) (2026.5.20)
Requirement already satisfied: yfinance in e:\anaconda\lib\site-packages (1.5.2)
Requirement already satisfied: pandas>=1.3.0 in e:\anaconda\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in e:\anaconda\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in e:\anaconda\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in e:\anaconda\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in e:\anaconda\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in e:\anaconda\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: peewee>=3.16.2 in e:\anaconda\lib\site-packages (from yfinance) (4.2.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in e:\anaconda\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in e:\anaconda\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in e:\anaconda\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in e:\anaconda\lib\site-packages (from yfinance) (16.1.1)
Requirement already satisfied: soupsieve>1.2 in e:\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in e:\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in e:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in e:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in e:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in e:\anaconda\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in e:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [2]:
import pandas as pd
import numpy as np
import datetime as dt
from pandas_datareader import data as pdr
import yfinance as yf

### Phase 1 : Data collection

In [20]:

# Stock data collection
# Importing data of 50 stocks

stocks = ["AAPL","MSFT","NVDA","AVGO","ORCL",
    "AMZN","TSLA","HD","MCD","BKNG",
    "META","GOOGL","NFLX","DIS",
    "PG","KO","PEP","COST",
    "UNH","JNJ","ABBV","LLY","MRK",
    "JPM","BAC","WFC","GS","MS","BLK",
    "CAT","GE","HON","UPS","BA","DE",
    "XOM","CVX","COP",
    "NEE","DUK",
    "PLD","AMT",
    "LIN","SHW","FCX","ECL",
    "AMD","CRM","TMUS","ISRG"]

data = yf.download(stocks, start='2016-01-01', end=None)

print(data)

[*********************100%***********************]  49 of 50 completed

Price            Close                                                  \
Ticker            AAPL        ABBV         AMD         AMT        AMZN
Date
2016-01-04   23.709105   37.132984    2.770000   74.226471   31.849501
2016-01-05   23.114971   36.978271    2.750000   75.692581   31.689501
2016-01-06   22.662611   36.984718    2.510000   75.423920   31.632500
2016-01-07   21.706154   36.875149    2.280000   73.543297   30.396999
2016-01-08   21.820925   35.869648    2.140000   72.330513   30.352501
...                ...         ...         ...         ...         ...
2026-07-23  321.660004  256.920013  539.690002  164.649994  233.660004
2026-07-24  333.019989  259.359985  521.950012  166.669998  232.110001
2026-07-27  336.910004  256.910004  494.950012  166.740005  231.389999
2026-07-28  340.079987  263.200012  454.619995  171.500000  230.860001
2026-07-29  338.190002  263.299988  429.559998  179.259995  226.649994

Price                                                                   ...  \
Ticker            AVGO          BA        BAC        BKNG          BLK  ...
Date                                                                    ...
2016-01-04   10.836730  126.005119  13.054461   48.778637   256.778656  ...
2016-01-05   10.474185  126.516289  13.054461   47.420296   257.441620  ...
2016-01-06   10.152009  124.507408  12.776369   46.872730   254.512253  ...
2016-01-07    9.829071  119.287827  12.315529   45.716488   243.388535  ...
2016-01-08    9.764332  116.579399  12.077165   44.532440   237.260086  ...
...                ...         ...        ...         ...          ...  ...
2026-07-23  392.470001  209.229996  61.279999  172.830002  1037.160034  ...
2026-07-24  381.920013  209.520004  62.049999  177.460007  1055.670044  ...
2026-07-27  383.220001  211.500000  62.130001  186.789993  1062.140015  ...
2026-07-28  380.910004  221.559998  62.619999  199.309998  1097.550049  ...
2026-07-29  370.320007  214.009995  61.070000  201.300003  1079.189941  ...

Price         Volume                                                           \
Ticker           PEP        PG      PLD      SHW     TMUS       TSLA      UNH
Date
2016-01-04   6689000  11529800  2852100  3405000  4614200  102406500  4991000
2016-01-05   4893800   8133700  3262700  2271900  5553600   47802000  2816800
2016-01-06   5483400   9551000  3385000  2370900  7243800   56686500  2677300
2016-01-07   5440000  11973900  3902800  2640900  8091300   53314500  5277200
2016-01-08   4853500   9676400  4161500  3592800  3512900   54421500  4422400
...              ...       ...      ...      ...      ...        ...      ...
2026-07-23   7755700   6499200  7444400  2446300  9626400  115606400  4868700
2026-07-24   7968300   6620700  6395400  2021300  5629200   62760000  3752500
2026-07-27   7237900   7301800  4110500  3207800  5494800   44919400  4615700
2026-07-28  10648800  12848800  5669200  3746300  4983200   39802400  5917300
2026-07-29   8390800  14606000  4092400  3370300  7257800   39207600  5257900

Price
Ticker           UPS       WFC       XOM
Date
2016-01-04   3730800  25985400  20400100
2016-01-05   2839600  14759600  11993500
2016-01-06   2443000  20026400  18826900
2016-01-07   3790800  30425600  21263800
2016-01-08   3941100  22981400  19033600
...              ...       ...       ...
2026-07-23   4198400  11220700  15822800
2026-07-24   3881100  11871400  12091600
2026-07-27   6719200  10379300  13955800
2026-07-28  14291000  16570500  16299900
2026-07-29   6032900  18050400  14571300

[2657 rows x 250 columns]

In [21]:
print(data.head())

Price           Close                                                    \
Ticker           AAPL       ABBV   AMD        AMT       AMZN       AVGO
Date
2016-01-04  23.709105  37.132984  2.77  74.226471  31.849501  10.836730
2016-01-05  23.114971  36.978271  2.75  75.692581  31.689501  10.474185
2016-01-06  22.662611  36.984718  2.51  75.423920  31.632500  10.152009
2016-01-07  21.706154  36.875149  2.28  73.543297  30.396999   9.829071
2016-01-08  21.820925  35.869648  2.14  72.330513  30.352501   9.764332

Price                                                     ...   Volume  \
Ticker              BA        BAC       BKNG         BLK  ...      PEP
Date                                                      ...
2016-01-04  126.005119  13.054461  48.778637  256.778656  ...  6689000
2016-01-05  126.516289  13.054461  47.420296  257.441620  ...  4893800
2016-01-06  124.507408  12.776369  46.872730  254.512253  ...  5483400
2016-01-07  119.287827  12.315529  45.716488  243.388535  ...  5440000
2016-01-08  116.579399  12.077165  44.532440  237.260086  ...  4853500

Price                                                                         \
Ticker            PG      PLD      SHW     TMUS       TSLA      UNH      UPS
Date
2016-01-04  11529800  2852100  3405000  4614200  102406500  4991000  3730800
2016-01-05   8133700  3262700  2271900  5553600   47802000  2816800  2839600
2016-01-06   9551000  3385000  2370900  7243800   56686500  2677300  2443000
2016-01-07  11973900  3902800  2640900  8091300   53314500  5277200  3790800
2016-01-08   9676400  4161500  3592800  3512900   54421500  4422400  3941100

Price
Ticker           WFC       XOM
Date
2016-01-04  25985400  20400100
2016-01-05  14759600  11993500
2016-01-06  20026400  18826900
2016-01-07  30425600  21263800
2016-01-08  22981400  19033600

[5 rows x 250 columns]

In [22]:
close_prices = data['Close']
print(close_prices)

Ticker            AAPL        ABBV         AMD         AMT        AMZN  \
Date
2016-01-04   23.709105   37.132984    2.770000   74.226471   31.849501
2016-01-05   23.114971   36.978271    2.750000   75.692581   31.689501
2016-01-06   22.662611   36.984718    2.510000   75.423920   31.632500
2016-01-07   21.706154   36.875149    2.280000   73.543297   30.396999
2016-01-08   21.820925   35.869648    2.140000   72.330513   30.352501
...                ...         ...         ...         ...         ...
2026-07-23  321.660004  256.920013  539.690002  164.649994  233.660004
2026-07-24  333.019989  259.359985  521.950012  166.669998  232.110001
2026-07-27  336.910004  256.910004  494.950012  166.740005  231.389999
2026-07-28  340.079987  263.200012  454.619995  171.500000  230.860001
2026-07-29  338.190002  263.299988  429.559998  179.259995  226.649994

Ticker            AVGO          BA        BAC        BKNG          BLK  ...  \
Date                                                                    ...
2016-01-04   10.836730  126.005119  13.054461   48.778637   256.778656  ...
2016-01-05   10.474185  126.516289  13.054461   47.420296   257.441620  ...
2016-01-06   10.152009  124.507408  12.776369   46.872730   254.512253  ...
2016-01-07    9.829071  119.287827  12.315529   45.716488   243.388535  ...
2016-01-08    9.764332  116.579399  12.077165   44.532440   237.260086  ...
...                ...         ...        ...         ...          ...  ...
2026-07-23  392.470001  209.229996  61.279999  172.830002  1037.160034  ...
2026-07-24  381.920013  209.520004  62.049999  177.460007  1055.670044  ...
2026-07-27  383.220001  211.500000  62.130001  186.789993  1062.140015  ...
2026-07-28  380.910004  221.559998  62.619999  199.309998  1097.550049  ...
2026-07-29  370.320007  214.009995  61.070000  201.300003  1079.189941  ...

Ticker             PEP          PG         PLD         SHW        TMUS  \
Date
2016-01-04   71.665520   58.231106   30.973524   76.986443   37.247650
2016-01-05   72.158897   58.416859   31.624050   77.297722   38.462139
2016-01-06   72.180702   57.852177   31.454012   75.061417   38.299572
2016-01-07   70.794838   57.346912   30.633471   73.003410   38.739468
2016-01-08   70.533623   56.447838   30.359962   73.063820   38.137009
...                ...         ...         ...         ...         ...
2026-07-23  134.949997  145.880997  145.119995  310.540009  170.419998
2026-07-24  136.639999  147.410004  147.630005  317.510010  180.089996
2026-07-27  139.789993  148.630005  147.259995  327.269989  177.210007
2026-07-28  142.860001  148.880005  147.119995  354.269989  182.389999
2026-07-29  143.500000  146.100006  145.470001  343.880005  181.520004

Ticker            TSLA         UNH         UPS        WFC         XOM
Date
2016-01-04   14.894000   97.893661   63.806980  39.475040   49.319611
2016-01-05   14.895333   98.078606   64.439415  39.460136   49.739861
2016-01-06   14.602667   97.078308   63.524410  38.706593   49.325981
2016-01-07   14.376667   94.220352   62.299953  37.602390   48.536465
2016-01-08   14.066667   92.598045   61.485878  36.975689   47.555939
...                ...         ...         ...        ...         ...
2026-07-23  319.690002  423.559998  114.099998  86.190002  156.889999
2026-07-24  313.029999  420.739990  114.790001  86.309998  156.940002
2026-07-27  309.220001  417.640015  112.949997  87.269997  154.770004
2026-07-28  307.440002  428.790009  105.529999  86.870003  153.039993
2026-07-29  298.320007  420.570007  104.559998  83.870003  156.750000

[2657 rows x 50 columns]

In [23]:
stock_prices = data.xs("Close", axis=1, level="Price")
stock_prices

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,23.709105,37.132984,2.770000,74.226471,31.849501,10.836730,126.005119,13.054461,48.778637,256.778656,...,71.665520,58.231106,30.973524,76.986443,37.247650,14.894000,97.893661,63.806980,39.475040,49.319611
2016-01-05,23.114971,36.978271,2.750000,75.692581,31.689501,10.474185,126.516289,13.054461,47.420296,257.441620,...,72.158897,58.416859,31.624050,77.297722,38.462139,14.895333,98.078606,64.439415,39.460136,49.739861
2016-01-06,22.662611,36.984718,2.510000,75.423920,31.632500,10.152009,124.507408,12.776369,46.872730,254.512253,...,72.180702,57.852177,31.454012,75.061417,38.299572,14.602667,97.078308,63.524410,38.706593,49.325981
2016-01-07,21.706154,36.875149,2.280000,73.543297,30.396999,9.829071,119.287827,12.315529,45.716488,243.388535,...,70.794838,57.346912,30.633471,73.003410,38.739468,14.376667,94.220352,62.299953,37.602390,48.536465
2016-01-08,21.820925,35.869648,2.140000,72.330513,30.352501,9.764332,116.579399,12.077165,44.532440,237.260086,...,70.533623,56.447838,30.359962,73.063820,38.137009,14.066667,92.598045,61.485878,36.975689,47.555939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-23,321.660004,256.920013,539.690002,164.649994,233.660004,392.470001,209.229996,61.279999,172.830002,1037.160034,...,134.949997,145.880997,145.119995,310.540009,170.419998,319.690002,423.559998,114.099998,86.190002,156.889999
2026-07-24,333.019989,259.359985,521.950012,166.669998,232.110001,381.920013,209.520004,62.049999,177.460007,1055.670044,...,136.639999,147.410004,147.630005,317.510010,180.089996,313.029999,420.739990,114.790001,86.309998,156.940002
2026-07-27,336.910004,256.910004,494.950012,166.740005,231.389999,383.220001,211.500000,62.130001,186.789993,1062.140015,...,139.789993,148.630005,147.259995,327.269989,177.210007,309.220001,417.640015,112.949997,87.269997,154.770004
2026-07-28,340.079987,263.200012,454.619995,171.500000,230.860001,380.910004,221.559998,62.619999,199.309998,1097.550049,...,142.860001,148.880005,147.119995,354.269989,182.389999,307.440002,428.790009,105.529999,86.870003,153.039993
2026-07-29,338.190002,263.299988,429.559998,179.259995,226.649994,370.320007,214.009995,61.070000,201.300003,1079.189941,...,143.500000,146.100006,145.470001,343.880005,181.520004,298.320007,420.570007,104.559998,83.870003,156.750000

In [25]:
stock_prices.head()

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,23.709105,37.132984,2.77,74.226471,31.849501,10.836730,126.005119,13.054461,48.778637,256.778656,...,71.665520,58.231106,30.973524,76.986443,37.247650,14.894000,97.893661,63.806980,39.475040,49.319611
2016-01-05,23.114971,36.978271,2.75,75.692581,31.689501,10.474185,126.516289,13.054461,47.420296,257.441620,...,72.158897,58.416859,31.624050,77.297722,38.462139,14.895333,98.078606,64.439415,39.460136,49.739861
2016-01-06,22.662611,36.984718,2.51,75.423920,31.632500,10.152009,124.507408,12.776369,46.872730,254.512253,...,72.180702,57.852177,31.454012,75.061417,38.299572,14.602667,97.078308,63.524410,38.706593,49.325981
2016-01-07,21.706154,36.875149,2.28,73.543297,30.396999,9.829071,119.287827,12.315529,45.716488,243.388535,...,70.794838,57.346912,30.633471,73.003410,38.739468,14.376667,94.220352,62.299953,37.602390,48.536465
2016-01-08,21.820925,35.869648,2.14,72.330513,30.352501,9.764332,116.579399,12.077165,44.532440,237.260086,...,70.533623,56.447838,30.359962,73.063820,38.137009,14.066667,92.598045,61.485878,36.975689,47.555939

In [26]:

benchmark = "SPY"

start_date = "2015-01-01"
end_date = None
import yfinance as yf

benchmark = "SPY"

benchmark_data = yf.download(
    benchmark,
    start=start_date,
    end=end_date,
    auto_adjust=True,
    progress=False
)

benchmark_prices = benchmark_data["Close"]
benchmark_prices.name = "SPY"
print(benchmark_data)

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date
2015-01-02  169.687851  170.885580  168.655335  170.472573  121465900
2015-01-05  166.623367  168.812297  166.317746  168.647097  169632600
2015-01-06  165.053925  167.449357  164.260947  166.928965  209151400
2015-01-07  167.110672  167.449340  165.929480  166.375521  125346700
2015-01-08  170.076096  170.290867  168.498420  168.514931  147217800
...                ...         ...         ...         ...        ...
2026-07-23  738.179993  742.559998  735.210022  739.369995   55437300
2026-07-24  738.929993  743.719971  737.289978  738.510010   44782000
2026-07-27  739.090027  745.530029  735.869995  744.909973   41461200
2026-07-28  740.859985  742.789978  735.979980  739.190002   47322200
2026-07-29  729.460022  742.679993  729.099976  739.969971   70473800

[2909 rows x 5 columns]

In [27]:
Benchmark_close_prices = benchmark_data["Close"]
Benchmark_close_prices

Ticker             SPY
Date
2015-01-02  169.687851
2015-01-05  166.623367
2015-01-06  165.053925
2015-01-07  167.110672
2015-01-08  170.076096
...                ...
2026-07-23  738.179993
2026-07-24  738.929993
2026-07-27  739.090027
2026-07-28  740.859985
2026-07-29  729.460022

[2909 rows x 1 columns]

In [28]:
stock_prices.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2657 entries, 2016-01-04 to 2026-07-29
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2657 non-null   float64
 1   ABBV    2657 non-null   float64
 2   AMD     2657 non-null   float64
 3   AMT     2657 non-null   float64
 4   AMZN    2657 non-null   float64
 5   AVGO    2657 non-null   float64
 6   BA      2657 non-null   float64
 7   BAC     2657 non-null   float64
 8   BKNG    2657 non-null   float64
 9   BLK     2657 non-null   float64
 10  CAT     2657 non-null   float64
 11  COP     2657 non-null   float64
 12  COST    2657 non-null   float64
 13  CRM     2657 non-null   float64
 14  CVX     2657 non-null   float64
 15  DE      2657 non-null   float64
 16  DIS     2657 non-null   float64
 17  DUK     2657 non-null   float64
 18  ECL     2657 non-null   float64
 19  FCX     2657 non-null   float64
 20  GE      2657 non-null   float64
 21  GOOGL   2657 non-null   float64
 22  GS      2657 non-null   float64
 23  HD      2657 non-null   float64
 24  HON     2657 non-null   float64
 25  ISRG    2657 non-null   float64
 26  JNJ     2657 non-null   float64
 27  JPM     2657 non-null   float64
 28  KO      2657 non-null   float64
 29  LIN     2657 non-null   float64
 30  LLY     2657 non-null   float64
 31  MCD     2657 non-null   float64
 32  META    2657 non-null   float64
 33  MRK     2657 non-null   float64
 34  MS      2657 non-null   float64
 35  MSFT    2657 non-null   float64
 36  NEE     2657 non-null   float64
 37  NFLX    2657 non-null   float64
 38  NVDA    2657 non-null   float64
 39  ORCL    2657 non-null   float64
 40  PEP     2657 non-null   float64
 41  PG      2657 non-null   float64
 42  PLD     2657 non-null   float64
 43  SHW     2657 non-null   float64
 44  TMUS    2657 non-null   float64
 45  TSLA    2657 non-null   float64
 46  UNH     2657 non-null   float64
 47  UPS     2657 non-null   float64
 48  WFC     2657 non-null   float64
 49  XOM     2657 non-null   float64
dtypes: float64(50)
memory usage: 1.0 MB

In [31]:
stock_prices.describe().T

,count,mean,std,min,25%,50%,75%,max
Ticker,,,,,,,,
AAPL,2657.0,123.005824,80.664196,20.565865,42.651619,127.185631,180.635315,340.079987
ABBV,2657.0,106.959159,56.448091,33.334942,60.964378,89.343391,143.488922,263.299988
AMD,2657.0,87.942721,88.479517,1.800000,18.830000,79.300003,119.160004,580.909973
AMT,2657.0,166.364263,47.002870,64.217026,119.057365,177.559097,200.868530,259.693481
AMZN,2657.0,126.813579,62.207862,24.103500,82.051498,121.660004,172.328506,274.989990
AVGO,2657.0,85.414693,104.288285,8.858731,20.109776,41.871212,94.360077,480.809052
BA,2657.0,219.401957,73.228784,95.010002,168.559998,207.520004,245.139999,430.299957
BAC,2657.0,29.853892,11.126491,8.867181,22.406261,27.203959,37.161869,62.619999
BKNG,2657.0,102.543943,48.370106,38.141788,70.597961,81.375031,126.245865,230.685989
BLK,2657.0,598.527005,252.555679,223.338120,377.896332,587.075378,773.477295,1183.469971
CAT,2657.0,222.425717,178.329139,45.614288,112.406944,173.370605,270.678192,1062.928223
COP,2657.0,66.337514,30.604062,18.056890,37.797195,53.268829,96.013908,132.812973
COST,2657.0,446.492777,291.864056,119.037163,190.220093,352.738495,576.789673,1092.582886
CRM,2657.0,180.828473,69.480660,53.130814,132.822098,177.701355,238.975586,363.219238
CVX,2657.0,107.182539,36.400744,41.190010,77.841919,89.546173,140.772705,209.233582
DE,2657.0,271.873663,152.275054,60.440575,131.662613,311.653595,384.828125,658.850281
DIS,2657.0,111.347023,24.889046,76.905746,94.418106,104.276825,119.332047,195.764511
DUK,2657.0,79.965616,21.733107,46.295631,61.215992,78.323563,91.654320,132.316620
ECL,2657.0,178.330764,51.975863,89.305687,134.911148,176.011856,214.199982,306.689972
FCX,2657.0,26.958974,15.959197,3.368377,11.669678,28.333921,39.028992,71.546341
GE,2657.0,110.315760,80.354507,26.567768,53.717464,78.028099,134.046967,378.679993
GOOGL,2657.0,112.757924,77.350140,33.757660,54.740108,93.778442,142.027634,402.379669
GS,2657.0,328.959460,216.652382,113.556511,183.084976,274.611847,362.423523,1152.069946
HD,2657.0,239.933004,92.391044,86.908241,153.349640,250.598938,320.057831,414.969330
HON,2657.0,159.579348,43.984679,72.913094,121.166252,171.421814,194.588074,258.714508
ISRG,2657.0,263.180399,144.330638,56.364445,161.860001,236.130005,353.559998,610.450012
JNJ,2657.0,134.296087,35.341314,71.791122,107.575363,138.190674,150.321609,267.239990
JPM,2657.0,135.250592,75.253008,40.193787,84.731766,112.227730,151.232590,357.309998
KO,2657.0,48.341139,13.434178,29.820889,36.006561,46.588036,56.890709,89.080002
LIN,2657.0,264.916680,131.871329,80.111313,140.787842,258.772034,391.312042,546.640015
LLY,2657.0,344.739754,322.202722,56.863182,94.790512,190.668732,582.422119,1235.560059
MCD,2657.0,201.457494,68.022771,87.571449,139.449158,204.048889,263.956909,336.880554
META,2657.0,296.802801,185.656418,88.136032,163.474442,209.074005,360.018463,787.419189
MRK,2657.0,72.252365,24.639976,33.546707,51.246170,66.020271,94.401169,131.820007
MS,2657.0,70.896149,44.802273,16.259533,35.798962,66.997871,86.939041,228.550003
MSFT,2657.0,231.807517,141.941145,42.818340,97.124207,228.038040,362.477203,538.658508
NEE,2657.0,55.038505,20.199830,19.765118,34.906898,60.931335,70.533165,97.168289
NFLX,2657.0,45.891498,29.085869,8.279000,26.308001,37.459000,59.374001,133.912994
NVDA,2657.0,44.594241,61.510943,0.614432,4.635846,13.609333,48.264202,235.465576
ORCL,2657.0,84.941945,56.391806,29.017603,43.691875,62.886684,111.561119,324.629974
PEP,2657.0,121.178717,30.345068,68.037621,89.126312,122.216995,149.535385,175.404282
PG,2657.0,112.066381,34.390139,55.712223,72.441597,118.845848,141.900711,171.262527
PLD,2657.0,86.118093,32.896152,26.294224,52.191895,91.351547,112.200096,151.876755
SHW,2657.0,215.919617,91.282672,72.332489,127.637207,222.533356,297.753143,394.284363
TMUS,2657.0,117.897247,59.392472,32.408802,62.962391,117.758034,146.231323,266.799194
TSLA,2657.0,163.226296,139.615612,9.578000,20.881332,174.839996,262.459991,489.880005
UNH,2657.0,319.078488,135.433369,91.816277,210.929214,298.666809,454.611267,599.775635
UPS,2657.0,108.527377,32.189144,59.676075,80.126915,95.952545,135.215439,187.075241
WFC,2657.0,46.597543,16.130448,18.556765,38.106022,42.064991,48.439770,95.373314
XOM,2657.0,73.696893,30.551680,23.823557,52.683285,57.602608,100.358330,170.313995

In [32]:
Benchmark_close_prices.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2909 entries, 2015-01-02 to 2026-07-29
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SPY     2909 non-null   float64
dtypes: float64(1)
memory usage: 45.5 KB

In [33]:
Benchmark_close_prices.describe().T

,count,mean,std,min,25%,50%,75%,max
Ticker,,,,,,,,
SPY,2909.0,354.352168,158.440457,154.161652,224.255585,317.48938,434.842255,757.618225

In [50]:
returns= np.log(stock_prices / stock_prices.shift(1)) # For calculating returns for each stocks
returns

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-05,-0.025379,-0.004175,-0.007246,0.019559,-0.005036,-0.034028,0.004049,0.000000,-0.028242,0.002579,...,0.006861,0.003185,0.020785,0.004035,0.032085,0.000090,0.001887,0.009863,-0.000378,0.008485
2016-01-06,-0.019764,0.000174,-0.091318,-0.003556,-0.001800,-0.031242,-0.016006,-0.021533,-0.011614,-0.011444,...,0.000302,-0.009713,-0.005391,-0.029358,-0.004236,-0.019844,-0.010251,-0.014301,-0.019281,-0.008356
2016-01-07,-0.043121,-0.002967,-0.096107,-0.025250,-0.039841,-0.032327,-0.042826,-0.036736,-0.024977,-0.044690,...,-0.019387,-0.008772,-0.026433,-0.027801,0.011420,-0.015598,-0.029882,-0.019464,-0.028942,-0.016136
2016-01-08,0.005274,-0.027646,-0.063370,-0.016628,-0.001465,-0.006608,-0.022967,-0.019545,-0.026241,-0.025502,...,-0.003697,-0.015802,-0.008969,0.000827,-0.015674,-0.021799,-0.017368,-0.013153,-0.016807,-0.020409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-23,-0.013065,0.014190,-0.023151,-0.008527,-0.046779,-0.010997,0.002776,-0.005533,-0.028688,-0.018598,...,-0.005174,-0.014590,0.002898,-0.029727,-0.113693,-0.156931,-0.018132,-0.015135,-0.002665,0.015675
2026-07-24,0.034707,0.009452,-0.033423,0.012194,-0.006656,-0.027249,0.001385,0.012487,0.026437,0.017689,...,0.012445,0.010427,0.017148,0.022197,0.055191,-0.021053,-0.006680,0.006029,0.001391,0.000319
2026-07-27,0.011613,-0.009491,-0.053115,0.000420,-0.003107,0.003398,0.009406,0.001288,0.051240,0.006110,...,0.022792,0.008242,-0.002509,0.030276,-0.016121,-0.012246,-0.007395,-0.016159,0.011061,-0.013923
2026-07-28,0.009365,0.024188,-0.084995,0.028148,-0.002293,-0.006046,0.046468,0.007856,0.064876,0.032795,...,0.021724,0.001681,-0.000951,0.079274,0.028812,-0.005773,0.026347,-0.067950,-0.004594,-0.011241
2026-07-29,-0.005573,0.000380,-0.056700,0.044254,-0.018405,-0.028196,-0.034671,-0.025064,0.009935,-0.016870,...,0.004470,-0.018849,-0.011279,-0.029767,-0.004781,-0.030113,-0.019356,-0.009234,-0.035145,0.023953

In [51]:
returns = returns.dropna() # Removing NaN values
returns

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-05,-0.025379,-0.004175,-0.007246,0.019559,-0.005036,-0.034028,0.004049,0.000000,-0.028242,0.002579,...,0.006861,0.003185,0.020785,0.004035,0.032085,0.000090,0.001887,0.009863,-0.000378,0.008485
2016-01-06,-0.019764,0.000174,-0.091318,-0.003556,-0.001800,-0.031242,-0.016006,-0.021533,-0.011614,-0.011444,...,0.000302,-0.009713,-0.005391,-0.029358,-0.004236,-0.019844,-0.010251,-0.014301,-0.019281,-0.008356
2016-01-07,-0.043121,-0.002967,-0.096107,-0.025250,-0.039841,-0.032327,-0.042826,-0.036736,-0.024977,-0.044690,...,-0.019387,-0.008772,-0.026433,-0.027801,0.011420,-0.015598,-0.029882,-0.019464,-0.028942,-0.016136
2016-01-08,0.005274,-0.027646,-0.063370,-0.016628,-0.001465,-0.006608,-0.022967,-0.019545,-0.026241,-0.025502,...,-0.003697,-0.015802,-0.008969,0.000827,-0.015674,-0.021799,-0.017368,-0.013153,-0.016807,-0.020409
2016-01-11,0.016063,-0.032323,0.089345,0.002649,0.017456,-0.001249,0.001691,0.007211,-0.000598,0.001753,...,0.002363,0.009172,-0.001218,0.000827,-0.005028,-0.015041,-0.005279,0.002950,0.010637,-0.013479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-23,-0.013065,0.014190,-0.023151,-0.008527,-0.046779,-0.010997,0.002776,-0.005533,-0.028688,-0.018598,...,-0.005174,-0.014590,0.002898,-0.029727,-0.113693,-0.156931,-0.018132,-0.015135,-0.002665,0.015675
2026-07-24,0.034707,0.009452,-0.033423,0.012194,-0.006656,-0.027249,0.001385,0.012487,0.026437,0.017689,...,0.012445,0.010427,0.017148,0.022197,0.055191,-0.021053,-0.006680,0.006029,0.001391,0.000319
2026-07-27,0.011613,-0.009491,-0.053115,0.000420,-0.003107,0.003398,0.009406,0.001288,0.051240,0.006110,...,0.022792,0.008242,-0.002509,0.030276,-0.016121,-0.012246,-0.007395,-0.016159,0.011061,-0.013923
2026-07-28,0.009365,0.024188,-0.084995,0.028148,-0.002293,-0.006046,0.046468,0.007856,0.064876,0.032795,...,0.021724,0.001681,-0.000951,0.079274,0.028812,-0.005773,0.026347,-0.067950,-0.004594,-0.011241
2026-07-29,-0.005573,0.000380,-0.056700,0.044254,-0.018405,-0.028196,-0.034671,-0.025064,0.009935,-0.016870,...,0.004470,-0.018849,-0.011279,-0.029767,-0.004781,-0.030113,-0.019356,-0.009234,-0.035145,0.023953

In [62]:
meanReturns = returns.mean()
meanReturns

Ticker
AAPL     0.001001
ABBV     0.000737
AMD      0.001899
AMT      0.000332
AMZN     0.000739
AVGO     0.001330
BA       0.000199
BAC      0.000581
BKNG     0.000534
BLK      0.000541
CAT      0.001015
COP      0.000469
COST     0.000748
CRM      0.000345
CVX      0.000458
DE       0.000849
DIS      0.000017
DUK      0.000385
ECL      0.000391
FCX      0.000873
GE       0.000374
GOOGL    0.000825
GS       0.000725
HD       0.000452
HON      0.000426
ISRG     0.000662
JNJ      0.000474
JPM      0.000741
KO       0.000403
LIN      0.000677
LLY      0.001075
MCD      0.000411
META     0.000660
MRK      0.000482
MS       0.000813
MSFT     0.000791
NEE      0.000564
NFLX     0.000716
NVDA     0.002065
ORCL     0.000508
PEP      0.000261
PG       0.000346
PLD      0.000582
SHW      0.000564
TMUS     0.000596
TSLA     0.001128
UNH      0.000549
UPS      0.000186
WFC      0.000284
XOM      0.000435
dtype: float64

In [52]:
returns.describe().T

,count,mean,std,min,25%,50%,75%,max
Ticker,,,,,,,,
AAPL,2656.0,0.001001,0.018197,-0.137708,-0.007128,0.001101,0.009987,0.142618
ABBV,2656.0,0.000737,0.016556,-0.177363,-0.006818,0.001087,0.008785,0.128985
AMD,2656.0,0.001899,0.037201,-0.277456,-0.017317,0.000769,0.020601,0.420617
AMT,2656.0,0.000332,0.016454,-0.164448,-0.007577,0.000806,0.008834,0.115308
AMZN,2656.0,0.000739,0.020570,-0.151398,-0.008992,0.001142,0.011520,0.126949
AVGO,2656.0,0.001330,0.024793,-0.222056,-0.010462,0.001352,0.013587,0.218594
BA,2656.0,0.000199,0.025923,-0.272444,-0.010456,0.000465,0.011443,0.217677
BAC,2656.0,0.000581,0.019410,-0.167204,-0.008474,0.000657,0.010350,0.163786
BKNG,2656.0,0.000534,0.020636,-0.145254,-0.008928,0.001066,0.010619,0.171868
BLK,2656.0,0.000541,0.017535,-0.146815,-0.007744,0.000827,0.009153,0.126843
CAT,2656.0,0.001015,0.019681,-0.154110,-0.008777,0.000928,0.011523,0.110061
COP,2656.0,0.000469,0.024203,-0.285552,-0.011343,0.000209,0.012976,0.224853
COST,2656.0,0.000748,0.013814,-0.132975,-0.005717,0.001074,0.007839,0.094942
CRM,2656.0,0.000345,0.022501,-0.219863,-0.009492,0.000755,0.011195,0.231468
CVX,2656.0,0.000458,0.018484,-0.250062,-0.007545,0.000925,0.008970,0.204904
DE,2656.0,0.000849,0.019066,-0.151663,-0.008212,0.000882,0.010315,0.126553
DIS,2656.0,0.000017,0.017907,-0.141139,-0.007621,-0.000101,0.008210,0.134639
DUK,2656.0,0.000385,0.012752,-0.122191,-0.005697,0.000920,0.006915,0.116011
ECL,2656.0,0.000391,0.015750,-0.124910,-0.006320,0.000909,0.007552,0.200170
FCX,2656.0,0.000873,0.032933,-0.227311,-0.015482,0.000522,0.018106,0.259935
GE,2656.0,0.000374,0.022526,-0.164394,-0.009587,0.000305,0.010766,0.137411
GOOGL,2656.0,0.000825,0.018294,-0.123685,-0.007778,0.001218,0.010210,0.097348
GS,2656.0,0.000725,0.018890,-0.135881,-0.008572,0.000706,0.010649,0.161951
HD,2656.0,0.000452,0.015727,-0.220570,-0.007060,0.000718,0.008475,0.128841
HON,2656.0,0.000426,0.014884,-0.128821,-0.005921,0.000870,0.007505,0.140356
ISRG,2656.0,0.000662,0.020434,-0.154739,-0.008283,0.001577,0.010285,0.160791
JNJ,2656.0,0.000474,0.011656,-0.105781,-0.004775,0.000477,0.006095,0.076940
JPM,2656.0,0.000741,0.017238,-0.162106,-0.007039,0.000864,0.008927,0.165620
KO,2656.0,0.000403,0.011529,-0.101728,-0.004778,0.000646,0.005960,0.062783
LIN,2656.0,0.000677,0.014309,-0.108513,-0.006367,0.000628,0.007836,0.110599
LLY,2656.0,0.001075,0.018779,-0.152411,-0.007613,0.001160,0.009369,0.145655
MCD,2656.0,0.000411,0.012792,-0.172870,-0.005374,0.000618,0.006533,0.166577
META,2656.0,0.000660,0.024588,-0.306390,-0.009629,0.000952,0.012227,0.209308
MRK,2656.0,0.000482,0.014411,-0.103840,-0.006599,0.000379,0.007883,0.099013
MS,2656.0,0.000813,0.019974,-0.169603,-0.008578,0.001157,0.011146,0.180404
MSFT,2656.0,0.000791,0.017101,-0.159453,-0.007009,0.000971,0.009745,0.132929
NEE,2656.0,0.000564,0.015829,-0.144067,-0.006653,0.001202,0.008297,0.128309
NFLX,2656.0,0.000716,0.026723,-0.432578,-0.011319,0.000483,0.013453,0.174189
NVDA,2656.0,0.002065,0.030893,-0.207712,-0.013281,0.002654,0.018303,0.260876
ORCL,2656.0,0.000508,0.021647,-0.148394,-0.007570,0.001027,0.009085,0.307108
PEP,2656.0,0.000261,0.012348,-0.121358,-0.005451,0.000450,0.006252,0.121657
PG,2656.0,0.000346,0.011918,-0.091429,-0.005283,0.000670,0.006431,0.113410
PLD,2656.0,0.000582,0.016974,-0.189596,-0.007653,0.001059,0.009596,0.111634
SHW,2656.0,0.000564,0.016821,-0.206741,-0.007706,0.000569,0.008884,0.134961
TMUS,2656.0,0.000596,0.016771,-0.118980,-0.007117,0.000826,0.008842,0.111387
TSLA,2656.0,0.001128,0.036884,-0.236518,-0.017596,0.001259,0.019587,0.204491
UNH,2656.0,0.000549,0.019071,-0.253341,-0.007009,0.000803,0.008700,0.120437
UPS,2656.0,0.000186,0.017221,-0.152134,-0.007616,0.000465,0.008514,0.134319
WFC,2656.0,0.000284,0.020131,-0.172779,-0.009016,0.000411,0.009917,0.135707
XOM,2656.0,0.000435,0.017617,-0.130391,-0.008231,0.000574,0.009362,0.119442

In [53]:
print(returns.isna().sum()) # For checking is there any NaN value present

Ticker
AAPL     0
ABBV     0
AMD      0
AMT      0
AMZN     0
AVGO     0
BA       0
BAC      0
BKNG     0
BLK      0
CAT      0
COP      0
COST     0
CRM      0
CVX      0
DE       0
DIS      0
DUK      0
ECL      0
FCX      0
GE       0
GOOGL    0
GS       0
HD       0
HON      0
ISRG     0
JNJ      0
JPM      0
KO       0
LIN      0
LLY      0
MCD      0
META     0
MRK      0
MS       0
MSFT     0
NEE      0
NFLX     0
NVDA     0
ORCL     0
PEP      0
PG       0
PLD      0
SHW      0
TMUS     0
TSLA     0
UNH      0
UPS      0
WFC      0
XOM      0
dtype: int64

In [54]:
print(Benchmark_returns.isna().sum())

Ticker
SPY    1
dtype: int64

In [55]:
Benchmark_returns= np.log(Benchmark_close_prices / Benchmark_close_prices.shift(1))# For calculating returns for benchmark
Benchmark_returns

Ticker           SPY
Date
2015-01-02       NaN
2015-01-05 -0.018225
2015-01-06 -0.009464
2015-01-07  0.012384
2015-01-08  0.017590
...              ...
2026-07-23 -0.012426
2026-07-24  0.001015
2026-07-27  0.000217
2026-07-28  0.002392
2026-07-29 -0.015507

[2909 rows x 1 columns]

In [56]:
Benchmark_returns.dropna()

Ticker           SPY
Date
2015-01-05 -0.018225
2015-01-06 -0.009464
2015-01-07  0.012384
2015-01-08  0.017590
2015-01-09 -0.008046
...              ...
2026-07-23 -0.012426
2026-07-24  0.001015
2026-07-27  0.000217
2026-07-28  0.002392
2026-07-29 -0.015507

[2908 rows x 1 columns]

In [44]:
stale = stock_prices.diff() == 0 # A stale price means the stock price didn't change for several consecutive trading days.
stale

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2016-01-05,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2016-01-06,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2016-01-07,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2016-01-08,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-07-23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2026-07-24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2026-07-27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2026-07-28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2026-07-29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [57]:
weights = np.ones(len(returns.columns)) / len(returns.columns) #Building weighted portions for 50 stocks
weights

array([0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02,
       0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02,
       0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02,
       0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02,
       0.02, 0.02, 0.02, 0.02, 0.02, 0.02])

In [69]:
# Weighted portfolio return series
portfolio_returns_50stocks = returns.dot(weights)
portfolio_returns_50stocks

Date
2016-01-05    0.001898
2016-01-06   -0.014162
2016-01-07   -0.028610
2016-01-08   -0.013358
2016-01-11   -0.002088
                ...
2026-07-23   -0.013859
2026-07-24    0.006227
2026-07-27    0.003746
2026-07-28    0.008909
2026-07-29   -0.012367
Length: 2656, dtype: float64

In [70]:
portfolio_returns = meanReturns.dot(weights)*252 # Expected annual portfolio return for 50 stocks
print(portfolio_returns)

0.16238877582171574

In [59]:
print(portfolio_returns.index.min())
print(portfolio_returns.index.max())

2016-01-05 00:00:00
2026-07-29 00:00:00

In [ ]:

import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf

In [65]:
mean_returns = portfolio_returns.mean()
print(mean_returns)

0.16238877582171574

In [71]:
# Covariance matrix
covMatrix = returns.cov()
covMatrix

Ticker,AAPL,ABBV,AMD,AMT,AMZN,AVGO,BA,BAC,BKNG,BLK,...,PEP,PG,PLD,SHW,TMUS,TSLA,UNH,UPS,WFC,XOM
Ticker,,,,,,,,,,,,,,,,,,,,,
AAPL,0.000331,0.000080,0.000288,0.000098,0.000211,0.000229,0.000188,0.000146,0.000157,0.000172,...,0.000086,0.000073,0.000141,0.000129,0.000106,0.000292,0.000099,0.000129,0.000132,0.000090
ABBV,0.000080,0.000274,0.000086,0.000072,0.000059,0.000074,0.000095,0.000097,0.000072,0.000095,...,0.000069,0.000062,0.000084,0.000085,0.000074,0.000070,0.000101,0.000078,0.000093,0.000079
AMD,0.000288,0.000086,0.001384,0.000095,0.000333,0.000439,0.000274,0.000207,0.000228,0.000245,...,0.000062,0.000052,0.000182,0.000172,0.000134,0.000511,0.000127,0.000187,0.000179,0.000103
AMT,0.000098,0.000072,0.000095,0.000271,0.000077,0.000074,0.000106,0.000086,0.000078,0.000120,...,0.000101,0.000088,0.000168,0.000113,0.000088,0.000088,0.000086,0.000082,0.000079,0.000056
AMZN,0.000211,0.000059,0.000333,0.000077,0.000423,0.000232,0.000166,0.000126,0.000177,0.000163,...,0.000052,0.000046,0.000125,0.000115,0.000102,0.000311,0.000079,0.000121,0.000114,0.000055
AVGO,0.000229,0.000074,0.000439,0.000074,0.000232,0.000615,0.000242,0.000176,0.000201,0.000208,...,0.000060,0.000042,0.000139,0.000156,0.000102,0.000378,0.000099,0.000124,0.000160,0.000102
BA,0.000188,0.000095,0.000274,0.000106,0.000166,0.000242,0.000672,0.000259,0.000262,0.000221,...,0.000083,0.000067,0.000172,0.000152,0.000113,0.000300,0.000135,0.000137,0.000267,0.000189
BAC,0.000146,0.000097,0.000207,0.000086,0.000126,0.000176,0.000259,0.000377,0.000198,0.000229,...,0.000072,0.000064,0.000141,0.000134,0.000107,0.000201,0.000124,0.000144,0.000326,0.000174
BKNG,0.000157,0.000072,0.000228,0.000078,0.000177,0.000201,0.000262,0.000198,0.000426,0.000180,...,0.000065,0.000055,0.000116,0.000119,0.000109,0.000222,0.000098,0.000109,0.000197,0.000119
BLK,0.000172,0.000095,0.000245,0.000120,0.000163,0.000208,0.000221,0.000229,0.000180,0.000307,...,0.000087,0.000077,0.000160,0.000160,0.000111,0.000229,0.000125,0.000141,0.000214,0.000123
CAT,0.000131,0.000085,0.000245,0.000058,0.000123,0.000206,0.000229,0.000222,0.000161,0.000193,...,0.000053,0.000048,0.000123,0.000127,0.000074,0.000184,0.000092,0.000146,0.000206,0.000169
COP,0.000126,0.000108,0.000184,0.000071,0.000091,0.000166,0.000253,0.000244,0.000161,0.000169,...,0.000067,0.000047,0.000116,0.000083,0.000098,0.000175,0.000115,0.000110,0.000229,0.000339
COST,0.000115,0.000055,0.000135,0.000073,0.000113,0.000108,0.000089,0.000074,0.000078,0.000100,...,0.000076,0.000069,0.000093,0.000087,0.000078,0.000136,0.000073,0.000079,0.000072,0.000047
CRM,0.000199,0.000080,0.000297,0.000107,0.000244,0.000222,0.000184,0.000151,0.000197,0.000179,...,0.000070,0.000051,0.000134,0.000134,0.000126,0.000308,0.000109,0.000114,0.000138,0.000082
CVX,0.000106,0.000092,0.000138,0.000073,0.000069,0.000141,0.000217,0.000195,0.000139,0.000143,...,0.000068,0.000047,0.000108,0.000083,0.000086,0.000136,0.000113,0.000097,0.000184,0.000271
DE,0.000126,0.000085,0.000188,0.000072,0.000102,0.000159,0.000230,0.000191,0.000138,0.000169,...,0.000068,0.000062,0.000122,0.000131,0.000090,0.000168,0.000104,0.000122,0.000182,0.000148
DIS,0.000137,0.000065,0.000191,0.000076,0.000140,0.000150,0.000214,0.000183,0.000188,0.000166,...,0.000070,0.000060,0.000118,0.000115,0.000095,0.000198,0.000082,0.000114,0.000169,0.000123
DUK,0.000053,0.000058,0.000024,0.000118,0.000020,0.000036,0.000086,0.000066,0.000050,0.000075,...,0.000093,0.000082,0.000112,0.000075,0.000067,0.000024,0.000075,0.000052,0.000073,0.000067
ECL,0.000132,0.000081,0.000172,0.000116,0.000112,0.000139,0.000179,0.000161,0.000152,0.000166,...,0.000092,0.000089,0.000136,0.000156,0.000097,0.000162,0.000102,0.000105,0.000152,0.000095
FCX,0.000203,0.000124,0.000410,0.000090,0.000204,0.000323,0.000357,0.000304,0.000255,0.000278,...,0.000065,0.000056,0.000172,0.000180,0.000114,0.000369,0.000140,0.000183,0.000279,0.000255
GE,0.000137,0.000081,0.000219,0.000072,0.000123,0.000197,0.000302,0.000230,0.000204,0.000188,...,0.000056,0.000057,0.000134,0.000133,0.000088,0.000202,0.000097,0.000119,0.000229,0.000156
GOOGL,0.000196,0.000075,0.000281,0.000079,0.000239,0.000218,0.000176,0.000137,0.000169,0.000165,...,0.000064,0.000055,0.000119,0.000115,0.000097,0.000266,0.000097,0.000104,0.000129,0.000074
GS,0.000158,0.000085,0.000246,0.000077,0.000146,0.000212,0.000257,0.000294,0.000192,0.000225,...,0.000064,0.000054,0.000136,0.000134,0.000100,0.000231,0.000116,0.000137,0.000278,0.000151
HD,0.000138,0.000085,0.000186,0.000111,0.000131,0.000156,0.000172,0.000143,0.000126,0.000162,...,0.000093,0.000079,0.000149,0.000170,0.000099,0.000176,0.000105,0.000126,0.000140,0.000080
HON,0.000122,0.000079,0.000159,0.000085,0.000094,0.000146,0.000215,0.000170,0.000144,0.000159,...,0.000076,0.000067,0.000118,0.000123,0.000083,0.000141,0.000100,0.000109,0.000166,0.000119
ISRG,0.000191,0.000099,0.000276,0.000110,0.000199,0.000222,0.000214,0.000155,0.000186,0.000190,...,0.000080,0.000072,0.000151,0.000148,0.000110,0.000266,0.000125,0.000112,0.000146,0.000093
JNJ,0.000061,0.000084,0.000041,0.000078,0.000034,0.000031,0.000070,0.000069,0.000044,0.000076,...,0.000075,0.000071,0.000075,0.000064,0.000056,0.000027,0.000077,0.000060,0.000066,0.000058
JPM,0.000129,0.000090,0.000177,0.000076,0.000107,0.000168,0.000241,0.000295,0.000180,0.000202,...,0.000068,0.000059,0.000125,0.000119,0.000092,0.000176,0.000114,0.000123,0.000278,0.000153
KO,0.000068,0.000065,0.000047,0.000091,0.000038,0.000049,0.000103,0.000079,0.000080,0.000081,...,0.000102,0.000085,0.000091,0.000078,0.000070,0.000048,0.000068,0.000058,0.000081,0.000072
LIN,0.000120,0.000081,0.000160,0.000092,0.000093,0.000133,0.000164,0.000142,0.000131,0.000144,...,0.000078,0.000071,0.000115,0.000124,0.000089,0.000136,0.000100,0.000098,0.000135,0.000100
LLY,0.000091,0.000116,0.000106,0.000077,0.000077,0.000085,0.000084,0.000076,0.000066,0.000089,...,0.000070,0.000070,0.000090,0.000082,0.000067,0.000071,0.000092,0.000067,0.000078,0.000058
MCD,0.000088,0.000064,0.000082,0.000092,0.000061,0.000090,0.000126,0.000096,0.000088,0.000100,...,0.000080,0.000068,0.000093,0.000095,0.000076,0.000098,0.000084,0.000063,0.000096,0.000070
META,0.000225,0.000067,0.000339,0.000083,0.000304,0.000261,0.000193,0.000153,0.000194,0.000182,...,0.000061,0.000053,0.000132,0.000135,0.000100,0.000306,0.000084,0.000125,0.000141,0.000067
MRK,0.000070,0.000104,0.000054,0.000072,0.000037,0.000049,0.000073,0.000080,0.000058,0.000080,...,0.000071,0.000069,0.000080,0.000073,0.000058,0.000049,0.000087,0.000061,0.000073,0.000065
MS,0.000172,0.000095,0.000269,0.000092,0.000154,0.000227,0.000271,0.000321,0.000214,0.000248,...,0.000074,0.000061,0.000153,0.000144,0.000107,0.000243,0.000130,0.000147,0.000299,0.000165
MSFT,0.000202,0.000079,0.000269,0.000101,0.000228,0.000224,0.000165,0.000135,0.000159,0.000168,...,0.000077,0.000066,0.000125,0.000118,0.000109,0.000256,0.000107,0.000110,0.000123,0.000071
NEE,0.000086,0.000062,0.000094,0.000136,0.000067,0.000078,0.000110,0.000069,0.000062,0.000100,...,0.000098,0.000089,0.000133,0.000094,0.000079,0.000096,0.000075,0.000073,0.000072,0.000066
NFLX,0.000200,0.000067,0.000331,0.000076,0.000280,0.000226,0.000169,0.000116,0.000173,0.000156,...,0.000055,0.000045,0.000105,0.000111,0.000124,0.000316,0.000084,0.000101,0.000097,0.000054
NVDA,0.000296,0.000086,0.000698,0.000100,0.000340,0.000463,0.000266,0.000195,0.000247,0.000254,...,0.000064,0.000052,0.000170,0.000178,0.000140,0.000489,0.000124,0.000167,0.000174,0.000096
ORCL,0.000138,0.000063,0.000265,0.000072,0.000152,0.000246,0.000152,0.000141,0.000134,0.000150,...,0.000059,0.000051,0.000107,0.000095,0.000071,0.000202,0.000089,0.000101,0.000135,0.000073
PEP,0.000086,0.000069,0.000062,0.000101,0.000052,0.000060,0.000083,0.000072,0.000065,0.000087,...,0.000152,0.000100,0.000101,0.000087,0.000083,0.000061,0.000077,0.000069,0.000072,0.000063
PG,0.000073,0.000062,0.000052,0.000088,0.000046,0.000042,0.000067,0.000064,0.000055,0.000077,...,0.000100,0.000142,0.000088,0.000076,0.000066,0.000040,0.000067,0.000070,0.000062,0.000044
PLD,0.000141,0.000084,0.000182,0.000168,0.000125,0.000139,0.000172,0.000141,0.000116,0.000160,...,0.000101,0.000088,0.000288,0.000145,0.000091,0.000165,0.000102,0.000130,0.000137,0.000086
SHW,0.000129,0.000085,0.000172,0.000113,0.000115,0.000156,0.000152,0.000134,0.000119,0.000160,...,0.000087,0.000076,0.000145,0.000283,0.000092,0.000161,0.000100,0.000113,0.000127,0.000062
TMUS,0.000106,0.000074,0.000134,0.000088,0.000102,0.000102,0.000113,0.000107,0.000109,0.000111,...,0.000083,0.000066,0.000091,0.000092,0.000281,0.000122,0.000096,0.000076,0.000099,0.000072
TSLA,0.000292,0.000070,0.000511,0.000088,0.000311,0.000378,0.000300,0.000201,0.000222,0.000229,...,0.000061,0.000040,0.000165,0.000161,0.000122,0.001360,0.000110,0.000134,0.000191,0.000094
UNH,0.000099,0.000101,0.000127,0.000086,0.000079,0.000099,0.000135,0.000124,0.000098,0.000125,...,0.000077,0.000067,0.000102,0.000100,0.000096,0.000110,0.000364,0.000086,0.000117,0.000086
UPS,0.000129,0.000078,0.000187,0.000082,0.000121,0.000124,0.000137,0.000144,0.000109,0.000141,...,0.000069,0.000070,0.000130,0.000113,0.000076,0.000134,0.000086,0.000297,0.000135,0.000091
WFC,0.000132,0.000093,0.000179,0.000079,0.000114,0.000160,0.000267,0.000326,0.000197,0.000214,...,0.000072,0.000062,0.000137,0.000127,0.000099,0.000191,0.000117,0.000135,0.000405,0.000172
XOM,0.000090,0.000079,0.000103,0.000056,0.000055,0.000102,0.000189,0.000174,0.000119,0.000123,...,0.000063,0.000044,0.000086,0.000062,0.000072,0.000094,0.000086,0.000091,0.000172,0.000310

In [73]:
portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(covMatrix * 252, weights)))
print(portfolio_volatility)

0.18383432326877275